# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test .NET Solution

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish FileSearchAndRenameApp.sln --configuration Release --output ./publish --self-contained --runtime win-x64

    - name: Zip published files
      run: |
        sudo apt-get install -y zip  # Install zip utility if not present
        cd publish  # Change to the publish directory
        zip -r FileSearchAndRenameApp.zip .  # Zip the contents of the publish directory
        cd ..  # Change back to the previous directory

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: FileSearchAndRenameApp
        path: FileSearchAndRenameApp.zip  # Upload the zip file instead of the directory

    - name: List the files
      run: ls -al

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: FileSearchAndRenameApp.zip  # Attach the zip file to the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
